# Generated by Django 4.1.8 on 2023-04-28 06:28

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_homepage_carousel_image_1_homepage_carousel_image_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="intro",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
