# Generated by Django 4.1.8 on 2023-04-28 06:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_homepage_intro"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="carousel_image_1",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="carousel_image_2",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="intro",
        ),
    ]
