# Generated by Django 4.1.8 on 2023-04-30 12:07

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("home", "0009_alter_homepage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("phone_number", wagtail.fields.RichTextField(blank=True)),
                ("email", wagtail.fields.RichTextField(blank=True)),
                ("address", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
