# Generated by Django 4.1.8 on 2023-05-06 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_footerpage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FooterPage",
        ),
    ]
