# Generated by Django 4.1.8 on 2023-05-12 07:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_contactpage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactPage",
        ),
    ]
